[package]
name = "mbf_gtf"
version = "0.1.2"
authors = ["Florian Finkernagel <finkernagel@imt.uni-marburg.de>"]

[lib]
crate-type=["cdylib"]
name = "mbf_gtf"

[dependencies]
hashbrown = "0.1"

[dependencies.pyo3]
version = "0.6.0-alpha.4"
features = ["extension-module"]

